### ISSUE TITLE
Hey, a Question

### ISSUE THREAD

**Issue by Smartin-b** [pitbox46/fightnbtintegration#10]
I kinda used your mod as a basis for
https://github.com/Smartin-b/art_of_forging
a fork that would allow Tetra to work with Better Combat
Hope thats okay as you are under the MiT license, 
otherwise i would have write custom net and config code *_*

**Comment by pitbox46** [comment]
This is fine as long as you follow the license. This is the only real limitation of the license
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
