### ISSUE TITLE
Some incompatible problems about 'Yamatomoveset Epicfight'(1.18.2) and this  mod.

### ISSUE THREAD

**Issue by YuanEternalR** [pitbox46/fightnbtintegration#16]
I add these two mods at the same time in a 1.18.2 java modpack.However, it crashs accidentally. After analyzing the crash report, I found that this mod will cast Yamato's weapon type. However, the type of Yamato is special, and it can't be switched. I want to know how to negotiate it. THX.

**Comment by pitbox46** [comment]
The crash report would be very helpful

**Comment by YuanEternalR** [comment]
> The crash report would be very helpful

![crash-2024-03-28_17.36.36-server.txt](https://github.com/pitbox46/fightnbtintegration/files/14796590/crash-2024-03-28_17.36.36-server.txt)

This might be right one.

**Comment by pitbox46** [comment]
This won't be fixed unfortunately. Yamato uses an old version of Epic Fight that I'm no longer maintaining for. I can look into it again if the Yamato mod is updated for newer versions
