### ISSUE TITLE
Crash during startup since EpicFight 20.8.*

### ISSUE THREAD

**Issue by AlbusRex** [pitbox46/fightnbtintegration#19]
NBT integration causes a crash during startup when used alongside any version of Epic fight newer than 20.7.4

Steps to reproduce: Launching the problematic versions by themselves on a completely fresh instance

Minecraft version: 1.20.1
Forge version: 47.3.5
Full crash report :  [crash-2024-08-12_[REDACTED]-fml.txt](https://github.com/user-attachments/files/16588909/crash-2024-08-12_.REDACTED.-fml.txt)

**Comment by pitbox46** [comment]
Fixed

**Comment by AlbusRex** [comment]
I can confirm it is fixed, thank you very much :)
