### ISSUE TITLE
Requires a newer version of Forge

### ISSUE THREAD

**Issue by LunarArmageddon99** [pitbox46/fightnbtintegration#20]
Forge mods can be run on Neoforge by default, and that's what I'm doing for most of my mods right now.  But, when I try to run this one in particular on Neoforge, I get an error about needing a version .2 of forge when I only have a version .1
This happens on 1.20.1, both version 1.0.1 and 1.0.2

**Comment by pitbox46** [comment]
Epic Fight also targets forge 47.2.x, at least for the newer versions, so you would still have the issue even if I changed it on my mod. You could modify the `mods.toml` of Epic Fight and see if it runs, but I'd be doubtful.
