### ISSUE TITLE
1.16.5 minor bug with the crossbow (QoL improvment)

### ISSUE THREAD

**Issue by Shibva** [pitbox46/fightnbtintegration#3]
so a small detail I noted when using the modified crossbow with the new update, the correct animation now plays, but its not properly showing the FULL charge/cocked 

![image](https://user-images.githubusercontent.com/38770780/150271356-a0e6cbf7-3cd7-4fe1-8690-73aa5bfd5bc3.png)
modified crossbow when fully charged up

![image](https://user-images.githubusercontent.com/38770780/150271395-0835db12-94fa-4b90-88cc-54b940c33474.png)
Regular Crossbow when fully charged up

**Comment by Shibva** [comment]
on a further note, the crossbow load animation is not in sync with the custom charge time. To recreate this, create a crossbow made of netherite and then charge it while in third person

**Comment by pitbox46** [comment]
This is something that I can't really fix. I would need more compatibility from Epic Fight mod to go any further with the animation stuff. Also this is a bit outside the scope of this mod. This mod is intended to allow NBT tags to define a Epic Fight weapon. Anything outside of that scope is something I don't really want to deal with
