### ISSUE TITLE
1.18.2 Stuck on preparing spawn area for a new world.

### ISSUE THREAD

**Issue by Gelox1209** [pitbox46/fightnbtintegration#8]
[latest.log](https://github.com/pitbox46/fightnbtintegration/files/9312994/latest.log)
This only happens when the NBTIntegration mod is loaded.

**Comment by Gelox1209** [comment]
It seems this only happens on new worlds, if I unload fightnbtintegration mod, create a world, load the mod back in and open the world, there's no issues.

Attempting to load a world that hasn't been fully created yet due to the bug will also end up with the same issue(Where it gets stuck at preparing spawn area).

**Comment by pitbox46** [comment]
Looking into this. I imagine it's an issue with newer versions of Epic Fight.

**Comment by Gelox1209** [comment]
It seems this stopped happening after the newest Epic Fight update, and instead the issue is now turned into #9

**Comment by pitbox46** [comment]
Fixed. See #9
