### ISSUE TITLE
Can't create new worlds, can't enter existing worlds, crashes

### ISSUE THREAD

**Issue by AllenOW** [pitbox46/fightnbtintegration#9]
https://paste.fastmirror.net/?212605fc0271d68c#DFWriLB9AsUh4Y9bgUk2Fo4NBeK8gWxJHmjxshd4BUeo
This is a crash report, suspected to be a problem with this mod

**Comment by AllenOW** [comment]
EpicFight-18.3.0-beta.jar
fightnbtintegration-1.18.2-1.0.2.jar
minecraft1.18.2
forge40.169

**Comment by pitbox46** [comment]
Looking into this. I imagine it's an issue with newer versions of Epic Fight.

**Comment by pitbox46** [comment]
Fixed in latest commit and update on Curseforge
